add onChange method
nerdgeschoss/react-use-form-library pull request #37
Opened 2024-01-25 10:28 UTC by grcldq

fixes #36

2024-01-25 10:31 UTC, JensRavens requested changes

2024-01-25 10:31 UTC, JensRavens commented on src/form.ts
> +  #onChange?: (model: T) => void;
```suggestion
  #onChange?: (form: Form<T>) => void;
```

this way you can get the model or just the changes or any other state about the form.

2024-01-25 11:12 UTC, JensRavens requested changes
what I'm missing on this PR is some test coverage for the new method

2024-01-26 04:50 UTC, grcldq commented
> what I'm missing on this PR is some test coverage for the new method

added 2 tests for this, please check again.

2024-01-26 10:33 UTC, JensRavens approved these changes

2024-01-26 10:33 UTC, merged

2024-01-26 10:52 UTC, JensRavens reviewed
I found the following issues:
- font rendering still seems to be wrong (not blocking, but something we should look into)
- when typing the investment amount field, the bottom border becomes thicker when the first number is entered. If this is the active/focus state of this field, it should happen when the cursor enters/leaves, not depending on the content
- when I type 80.000 into the field, it is marked red without a validation error displayed
- the bottom border of the date input is always bold, no matter if it is active or not
- the placeholder "nächstmöglich" in the datefield should display a text cursor mouse cursor to indicate that you can edit it
- spacings around the dynamization slider are incorrect, the handle of the slider is bigger than in the spec